// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnUHpOThCHY0PSacqyrqU_q7b-EDEu298',
    appId: '1:514467017471:web:af838fd1b317d0346392ca',
    messagingSenderId: '514467017471',
    projectId: 'kanon-63c6d',
    authDomain: 'kanon-63c6d.firebaseapp.com',
    storageBucket: 'kanon-63c6d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAdcXIV1dz_680nX6u8pEdAgizCOfGunU',
    appId: '1:514467017471:android:36d2e38a9ff1d0686392ca',
    messagingSenderId: '514467017471',
    projectId: 'kanon-63c6d',
    storageBucket: 'kanon-63c6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVswolYWaVMSrkkrmLBCj-GcPOKtLkF5I',
    appId: '1:514467017471:ios:23eb06bd9bba8fad6392ca',
    messagingSenderId: '514467017471',
    projectId: 'kanon-63c6d',
    storageBucket: 'kanon-63c6d.appspot.com',
    iosBundleId: 'com.example.kanonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVswolYWaVMSrkkrmLBCj-GcPOKtLkF5I',
    appId: '1:514467017471:ios:91394d111e9cd5946392ca',
    messagingSenderId: '514467017471',
    projectId: 'kanon-63c6d',
    storageBucket: 'kanon-63c6d.appspot.com',
    iosBundleId: 'com.example.kanonApp.RunnerTests',
  );
}
